name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.10, 3.11, 3.12]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt || true  # optional if you have deps
        pip install pytest  # or skip this if using unittest only

    - name: Run tests with unittest
      run: |
        python -m unittest discover tests

    # Optional: Run with pytest instead
    # - name: Run tests with pytest
    #   run: |
    #     pytest
